### ISSUE TITLE
Synchronising Google Apps Scripts

### ISSUE THREAD

**Issue by peter-lyons-kehl** [peter-kehl/PowerMute#1]
Hi Gustavo @gustavorochakv,

Thank you for attaching a log to that Rclone issue.

Are you on Linux/Unix? You may want to use Eclipse https://developers.google.com/eclipse/docs/apps_script. It saves Google Apps Scripts file by file. It syncs them both ways.

**Comment by gustavorochakv** [comment]
Thanks for the tip, I didn't know that.

**Comment by peter-lyons-kehl** [comment]
Hi Gustavo @gustavorochakv,

Are you interested in Google Apps Scripts? Or, would you like to influence an add-on for GMail?

I'm starting one, and I'm searching for suggestions on a name. Could you drop me an email, please.
